# Generated by Django 3.2.8 on 2021-12-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='place',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='submited',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='type_of_event',
        ),
    ]
