# Generated by Django 3.2.8 on 2021-12-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_auto_20211205_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='building',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='residencial',
            field=models.CharField(max_length=128),
        ),
    ]
