# Generated by Django 3.2.8 on 2021-12-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_announcement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='announcement',
            name='valid_date',
            field=models.DateField(auto_now=True),
        ),
    ]
