# Generated by Django 3.2.8 on 2021-12-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_auto_20211212_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='submited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
