# Generated by Django 3.2.8 on 2021-12-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_announcement_submited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='valid_date',
            field=models.DateField(),
        ),
    ]
