# Generated by Django 3.2.8 on 2021-12-19 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_alter_announcement_valid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcer', to='building.profile'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=20000)),
                ('status', models.CharField(max_length=96)),
                ('reported_date', models.DateTimeField(auto_now=True)),
                ('signed_date', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='building.profile')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signer', to='building.profile')),
            ],
        ),
    ]
