# Generated by Django 3.2.8 on 2021-12-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='resident', max_length=64),
        ),
    ]
