# Generated by Django 3.2.8 on 2021-12-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_auto_20211219_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='reported_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='issues',
            name='signed_date',
            field=models.DateTimeField(),
        ),
    ]
