# Generated by Django 3.2.8 on 2021-12-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0008_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='residencial',
        ),
        migrations.AddField(
            model_name='announcement',
            name='valid_date',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
