# Generated by Django 3.2.8 on 2021-12-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0009_auto_20211212_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='valid_date',
        ),
    ]
