# Generated by Django 3.2.8 on 2021-12-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0010_remove_announcement_valid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='valid_date',
            field=models.DateTimeField(default='12/12/2021'),
        ),
    ]
