# Generated by Django 3.2.8 on 2021-12-19 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0010_alter_issues_signed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signer', to='building.profile'),
        ),
    ]
