# Generated by Django 3.2.8 on 2021-12-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0011_announcement_valid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='valid_date',
            field=models.DateTimeField(),
        ),
    ]
