# Generated by Django 3.2.8 on 2021-12-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0013_remove_announcement_valid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='submited',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
    ]
